### ISSUE TITLE
Please can you / we update the documentation in the jupyter notebook

### ISSUE THREAD

**Issue by David-Woroniuk** [rohan-paul/MachineLearning-DeepLearning-Code-for-my-YouTube-Channel#1]
The documentation hasn't translated well from Markdown to the Jupyter notebook, please can we modify the argument list within the Jupyter notebook?

Happy to share an updated version with you :)

**Comment by rohan-paul** [comment]
> The documentation hasn't translated well from Markdown to the Jupyter notebook, please can we modify the argument list within the Jupyter notebook?
> 
> Happy to share an updated version with you :)

Hi @David-Woroniuk - Thanks @David-Woroniuk for the reporting and apology for the late reply. I just corrected to the best extent that jupyter notebook was taking it.

**Comment by David-Woroniuk** [comment]
Thanks. Closing
