### ISSUE TITLE
Keyword arguments {'return_tensor': 'pt'} not recognized.

### ISSUE THREAD

**Issue by vistarsvo** [rohan-paul/MachineLearning-DeepLearning-Code-for-my-YouTube-Channel#5]
Hi. 
When i try to use example from [MachineLearning-DeepLearning-Code-for-my-YouTube-Channel](https://github.com/rohan-paul/MachineLearning-DeepLearning-Code-for-my-YouTube-Channel) in google colab after training model i've got next error:
![изображение](https://user-images.githubusercontent.com/5312683/194927368-faaefeec-97f9-4aa0-a421-7fcbb7970678.png)

Also, when i try use 'tf' got another error
![изображение](https://user-images.githubusercontent.com/5312683/194927534-9bbec03e-eb27-4146-9ba2-1feda94e9199.png)

**Comment by MaazBinMusa** [comment]
Facing exact issue.

**Comment by MaazBinMusa** [comment]
@vistarsvo I fixed the issue. It seems to be a typing mistake. use "return_tensors" instead of "return_tensor"
